### ISSUE TITLE
这个功能对于https的URL无效啊

### ISSUE THREAD

**Issue by kimizhu1984** [Riant/host-switch-plus#1]

**Comment by mylesshie** [comment]
我也表示遇到同样的问题

**Comment by kimizhu1984** [comment]
没人管，只能自力更生了。

修改model.js 大概341行左右，加上https的判断条件

var data='function FindProxyForURL(url,host){ \n if(shExpMatch(url,"http:_")||shExpMatch(url,"https:_")){if(isPlainHostName(host)){return "DIRECT";' +
                script + '}else{return "DIRECT";}}else{return "DIRECT";}}';

**Comment by kunnka** [comment]
model.js 在哪

**Comment by Riant** [comment]
@kimizhu1984 
哈哈，主要是还没找到好的办法，看了下 Chrome 的API, 看的云里雾里的；
你的方法我在 360浏览器上 测试了下好像也不行吧。

**Comment by Riant** [comment]
@kimizhu1984 
哦，已经修改上线了，最新版本号 1.3.9，之前测试无效是因为我的测试方法不对，同时 Fiddler 也没有开启 https 解密导致的。

谢谢。
