### ISSUE TITLE
能支持socks5代理么

### ISSUE THREAD

**Issue by friskfly** [Riant/host-switch-plus#13]
现在好像只支持http， 还不能完全取代 switchy

**Comment by Riant** [comment]
据不完全测试，http, https, socket 都支持的，不过不能像 switchy 那样分别设置，比如我对  ShadowSocks 的配置：

> IP: 127.0.0.1:1080
> domain: \* 

即可让所有访问都走 ShadowSocks 的代理设置。当然你具体设置的时候，还是看一下你的 ShadowSocks 的代理端口，可能和我的 1080 不一样
