### ISSUE TITLE
能否增加对不同的标签页配置不同的host的功能？

### ISSUE THREAD

**Issue by stevenztt** [Riant/host-switch-plus#14]
我需要打开多个页面，但是这些页面有些同样的url需要对应不同的ip。

**Comment by Riant** [comment]
这个没办法哈，代理设置是针对浏览器的。
况且，标签页本身是不固定的，即使能实现也会导致配置项庞杂难以管理哈。

但是我觉得，你在某一段时间的配置应该是相对固定的，毕竟你不可能同时浏览两个页签嘛。
所以，建议你在需要的时候，直接切换哈，现在浏览器插件式的切换方式已经非常简便了。
