### ISSUE TITLE
可以增加导出备份和排序的功能吗？

### ISSUE THREAD

**Issue by webkb** [Riant/host-switch-plus#15]
如果能云备份就更好了，另外hosts文件还是有他的用处的，如果本插件可以把hosts文件导进去，但是并不在控制面板里面直接显示就完美了，即常用切换在切换面板显示，不常用的就在另外一个面板显示。还有，如果能和ping.chinaz.com结合起来，自动选取最优ip的话就可以当作收费插件出售了。

**Comment by Riant** [comment]
这个插件的开发初衷本身就是为了开发者一个域名需要不断切换各种环境 IP，一些不是经常变更的绑定关系建议还是使用 hosts 文件配置，同时插件说明也对之类需求做了工具推荐。

至于最优 IP 之类属于翻墙范畴的需求，也可以使用 shadowsocks 之类配合该插件使用。
