### ISSUE TITLE
大小写敏感

### ISSUE THREAD

**Issue by qinjx** [Riant/host-switch-plus#17]
如果配置host表时使用的是小写，地址栏里域名部分字母大写了，host switch plus会先把域名转换成小写，然后还是拦截失败，会使用DNS解析的真实IP

但console里输出的hostname是正确的

我配置的是*.xxx.com。没有试过不使用通配符是不是也存在这个问题

**Comment by webkb** [comment]
大小写有问题我不知道，如果host switch plus的ip不可访问的话，仍然会访问真实IP，而不是直接失败，这和hosts不太一样，我觉得hosts文件方式更好

**Comment by Riant** [comment]
大小写没有具体测试过，还是自己控制一下输入比较好。
如果是不需要经常切换的 host 配置，最好还是配置到 hosts 文件里边去。

@webkb  是的，这可能是 Chrome 代理接口从访问者角度出发的逻辑吧，这样可能会导致一些测试上的误解，需要注意。
