### ISSUE TITLE
启动插件后会影响shadowsocks的使用，如何解决？

### ISSUE THREAD

**Issue by xhay1122** [Riant/host-switch-plus#18]

**Comment by Riant** [comment]
shadowsocks 我使用的是小飞机图标那个，他不是全局大理的，而是提供代理端口，可以通过给插件配置

> IP:127.0.0.1:1080 domain:*

其中 1080 端口要具体看你的 shadowsocks 的端口，然后在需要使用的时候启用该配置，
或者也可以针对某个域名一直启用，比如：

> 127.0.0.1:1080    *.google.com
> 127.0.0.1:1080    *.googleusercontent.com
> 127.0.0.1:1080    *.gstatic.com

**Comment by xhay1122** [comment]
我也是用的小飞机图表的shadowsocks，但是当开启host-switch-plus后，chrome的代理就由该插件控制了，导致shadowsocks不能使用

**Comment by xhay1122** [comment]
今天尝试加一条如下规则：127.0.0.1 *
问题解决

**Comment by Riant** [comment]
嗯，我这里小飞机的本地代理端口是 1080，所以我一般是设置为：

> 127.0.0.1:1080     *

**Comment by xhay1122** [comment]
新问题是

> 127.0.0.1:1080 *
> 配置之后，访问所有的网站都会走小飞机，打开国内的网页就慢了:（

**Comment by Riant** [comment]
所以我也提了一下下面的配置方案：

> 127.0.0.1:1080 *.google.com
> 127.0.0.1:1080 *.googleusercontent.com
> 127.0.0.1:1080 *.gstatic.com

不过，域名多了也麻烦。

不过，小飞机本身是会区别对待国内和国外的吧。注意一下 PAC选项 和 系统代理模式设置为 PAC模式
