### ISSUE TITLE
和 Proxy SwitchyOmega 不能共用？

### ISSUE THREAD

**Issue by DrayChou** [Riant/host-switch-plus#19]
不是说可以共用的吗？但是不行啊。有什么解决办法吗？

**Comment by Riant** [comment]
不能共用哈，Chrome 的代理机制，仅允许一个代理类插件生效。

Host Switch plus 插件只是在 host switch 基本功能的基础上，简单实现了本地端口的代理功能。

如：

> 127.0.0.1:1080  *.google.com
> 127.0.0.1:1080  *.googleusercontent.com
> 127.0.0.1:1080  *.gstatic.com
> 127.0.0.1:1080   *

**Comment by DrayChou** [comment]
好吧，谢谢，现在只能装2个类chrome浏览器了，一个自用，一个开发。

Riant notifications@github.com 於 2016年4月16日週六 09:44 寫道：
