### ISSUE TITLE
设置hosts以后没生效

### ISSUE THREAD

**Issue by kunnka** [Riant/host-switch-plus#2]
不知道是不是另外一位仁兄说的https的问题

**Comment by Riant** [comment]
嗯，暂时还没有找到代理 https 请求的方法。

**Comment by Riant** [comment]
@kunnka
是 https 的问题，已经解决，可以更新版本(1.3.9)试试。
Double check: https://github.com/Riant/host-switch-plus/issues/1

**Comment by Riant** [comment]
@kunnka
是 https 的问题，已经解决，可以更新版本(1.3.9)试试。
Double check: https://github.com/Riant/host-switch-plus/issues/1
