### ISSUE TITLE
为什么我的扩展安装后打开链接是白屏

### ISSUE THREAD

**Issue by wang745125665** [Riant/host-switch-plus#20]
打开本地页面是空白，如果修改host文件就是正常的

**Comment by Riant** [comment]
这个要具体看你的程序配置哈，可能是程序里边有获取访问者 IP 之类的逻辑可能会出现问题。

不过这类问题我只是在安装本地 WordPress 的时候遇到过 WordPress 获取到的静态资源路径和 Site url 都不对的问题。

**Comment by wang745125665** [comment]
比如我在本地host文件配置  127.0.0.1 www.exp.com是可以访问，在扩展里面生效127.0.0.1 www.exp.com，打开就是空白，这扩展不应该跟替换host文件类似么

**Comment by Riant** [comment]
和替换 hosts 文件类似，但是不一样哈，hosts 那里是系统级别的处理，这里的浏览器级别的处理，会有很多底层的差异哈。

还是要具体看你的程序哈
