### ISSUE TITLE
关于charles

### ISSUE THREAD

**Issue by phpgoc** [Riant/host-switch-plus#21]
用了这个插件后，charles抓不到包，应该怎么设置可以解决？

**Comment by Riant** [comment]
不好意思，没用过 charles, 只在 Windows 上用过 Fiddler, 通过配置代理至 Fiddler 的端口实现，比如我的 Fiddler 端口是 8888：

> 127.0.0.1:8888    static.example.com

不知道 Charles 是不是类似。
