### ISSUE TITLE
如何解决hosts switch plus和Shadowsocks的冲突？

### ISSUE THREAD

**Issue by ruofeng086** [Riant/host-switch-plus#23]
如题，开启了hosts switch plus 插件后，Shadowsocks无法使用了，选system也不行。

望解决方案。

**Comment by Riant** [comment]
Shadowsocks 提供了本地代理端口的，可以双击任务栏的小飞机图标查看，比如我本地是 1080，设置需要代理的域名（也可以设置为 \* ）规则为 127.0.0.1:1080，并在需要时开启即可。
