### ISSUE TITLE
无法一键取消tag下的重复的 域名

### ISSUE THREAD

**Issue by premier815** [Riant/host-switch-plus#24]
例如，我在dev下配置了3个域名，其中有两个域名相同，点击 dev 的时候，没有任何变化。
1.1.1.1  a.abc.com
2.2.2.2  a.abc.com
3.3.3.3  b.abc.com

如果激活了 3.3.3.3  b.abc.com, 再次点击 dev 的时候，没有任何变化，无法关闭 3.3.3.3  b.abc.com，只能点击 3.3.3.3  b.abc.com 。

**Comment by Riant** [comment]
不是很明白的你的意图。
点击 tag 只是切换列表，之后再点击，则该列表（在没有全部启用的情况下）全部启用或者（在已经全部启用的情况下）全部取消，
如果当前列表下有相同域名，则会按照“相同域名，只有一个能被启用”的规则启用某一个，导致该列表不能全部启用，你再次点击标签，由于没有全部启用，会再次执行全部启用... 当然由于你有相同域名，所以该列表不可能全部启用。

如果要启用/取消某一个规则，需要直接点击该规则。当启用规则时，如果该域名有其他规则已经启用，则会被在启用该规则前取消。
