### ISSUE TITLE
与SwitchyOmega冲突

### ISSUE THREAD

**Issue by sm0king** [Riant/host-switch-plus#25]
你们的不冲突么？每次我启动Host Switch Plus 后 SwitchyOmega就不能用了，什么情况？要怎么配置才行么？

**Comment by Riant** [comment]
我也觉得会冲突，或者说应该只有其中一个会生效。但是看 SwitchyOmega 的安装说明：

> 特别提醒：由于Chrome限制，同一时间只能有一个扩展控制代理设置，一般来说Chrome会优先后安装的扩展。冲突中若SwitchyOmega获得了优先权，则可以切换到“系统代理”模式，从而把优先权归还给其他扩展，从而解决问题。如果此扩展的配置被其他代理相关、或者去广告相关的扩展覆盖，则问题无法解决，只能通过重装SwitchyOmega来提高优先权。

貌似不会冲突，只是优先级的问题，参见 #26
