### ISSUE TITLE
两个问题，麻烦看下

### ISSUE THREAD

**Issue by qindc** [Riant/host-switch-plus#26]
1、已经有人提到的，如果当前域名，我在插件上设置了指向的ip，把ip显示出来
2、之前用的switchySharp，优先级貌似地域本插件；但是升级使用switchyOmega后，优先级变了。建议把优先级拿回来，毕竟修改host，是人主观所为，更需要被支持。

插件非常棒，感谢作者！

**Comment by Riant** [comment]
1. 好的，我抽时间尽快弄一下；不过，目前版本，可以在 F12 的 Console 控制台中看到类似如下注释输出：
   
   > Host switch: 09:59:43 - test.xxx.com=>111.111.111.111
2. 这个优先级是 Chrome 自动处理的，即 switchyOmega 插件说明中描述的：
   
   > 特别提醒：由于Chrome限制，同一时间只能有一个扩展控制代理设置，一般来说Chrome会优先后安装的扩展。冲突中若SwitchyOmega获得了优先权，则可以切换到“系统代理”模式，从而把优先权归还给其他扩展，从而解决问题。如果此扩展的配置被其他代理相关、或者去广告相关的扩展覆盖，则问题无法解决，只能通过重装SwitchyOmega来提高优先权。

所以要把优先级拿回来的话，可以尝试重装 Host Switch Plus。

多说一点：Host Switch Plus 的 IP 支持端口设置
3. 如果只是简单使用 SwitchyOmega 的话，可以尝试配置 Host Switch Plus 的 IP 端口，以及 标签（类似其情景模式） 实现其主要功能。
如下配置将 facebook.com 代理至本地 1080 端口，即 Shadowsocks（你的本地端口可能和我的不一样，请双击 Shadowsocks 小飞机图标，配置界面的确定按钮上方有代理端口设置）

> 127.0.0.1:1080    *.facebook.com shadowsocks

更多的如：

> 127.0.0.1:1080  *.google.com.hk  shadowsocks
> 127.0.0.1:1080  *.gstatic.com    shadowsocks

甚至可以将 domain 配置为 \* ，在需要的时候开启即可：

> 127.0.0.1:1080  \* shadowsocks

**Comment by qsLI** [comment]
这个工具很赞。但是switchOmega的自动切换是有白名单的，使用起来还是不太方便，可否设置白名单，比如说这个工具只在相应的域名下生效？

**Comment by Riant** [comment]
您的意思是和 switchOmega 协同工作，让本插件只在所配置的域名下生效吗？根据 Chrome 官方说明，多个代理类插件是不能同时生效的。
暂时没办法哈。
