### ISSUE TITLE
一些疑问与建议

### ISSUE THREAD

**Issue by ScsUndefined** [Riant/host-switch-plus#28]
疑问： 
1. note 是用来干嘛的？备注？

建议：
1. 删除内置的 prod dev test 这三个 tag
    理由：用户会自己去建自己的 tag 名的...像我不需要生产环境和测试环境的 hosts，但是 prod 和 test 这两个 tag 又删不掉，各种蛋疼
1. 优化下 tag 的写法
   理由：我开发环境的 hosts 有几十个，然后开发环境还分数个，而且还经常变动，批量切换功能需要根据 tag 来，而 tag 编辑起来又贼不方便 需要每行都去改，建议采用 Google Chrome App "HostAdmin App" 的写法，简化编译 tag 的费力程度。
   附： HostAdmin Grouping 的写法约定地址 https://github.com/tg123/chrome-hostadmin/blob/master/README.markdown（在这个地址里搜 Grouping 就看到了）

附：感谢作者的辛勤开发～～～工具的确好用～～～

**Comment by Riant** [comment]
请更新至 1.3.10, 已经移除默认 Tags.

感谢反馈和建议，几十个代理规则，可怜的娃  :D ，批量修改的功能下一版本支持哈。

**Comment by ScsUndefined** [comment]
nice~
