### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by ihqn** [Riant/host-switch-plus#29]
使用

![image](https://cloud.githubusercontent.com/assets/4971364/18153344/7d4db0b6-702f-11e6-9e27-1b97580fc07d.png)

添加上就无法翻墙了。

**Comment by Riant** [comment]
请问你的翻墙插件是怎么配置的，Hosts Switch 本身就是配置代理的

**Comment by Riant** [comment]
上一张我配置 Shadowsocket 的截图哈：

![2016-09-09_155908](https://cloud.githubusercontent.com/assets/668285/18379881/575f3824-76a7-11e6-8d5e-544d78643efb.png)
