### ISSUE TITLE
请求头里的get参数问题，不能确定是否与这个插件有关~

### ISSUE THREAD

**Issue by minzhitang** [Riant/host-switch-plus#3]
您好，问题如下：

正常情况下，如我用ff下的其他插件绑host，或者直接改/etc/hosts，是这样子的：
![182fdb4f-0adb-4103-a89e-8e625a9cc7ce](https://cloud.githubusercontent.com/assets/680837/8951671/3d53a8fc-3602-11e5-9606-cbdd70cf8f38.jpg)

但如果是用host switch plus:
![847d781f-3bc1-42ae-982c-d40f557e6cda](https://cloud.githubusercontent.com/assets/680837/8951675/43f5eab2-3602-11e5-958d-30f31d873487.jpg)

**Comment by Riant** [comment]
你好，由于插件使用的是 PAC Script 方式代理，和其他插件通过修改 Hosts 或者手动修改 Hosts 文件的方式有所不同。
所以可能导致在安装某些 Web 程序时 Domain， Host 之类检测不准确而影响安装配置正确性。
如果你说的也是这个问题的话，建议安装的时候还是手动配置 Hosts 文件安装，安装完成之后再移除 相关host , 使用 host switch plus 代理。

插件尝试解决的，是对同一个 Domain 需要频繁切换 host，而 Hosts 文件配置又不能立即生效的应用场景问题。
对于不需要经常切换的 domain-host 配置，也建议使用 手动配置 Hosts 文件实现。

谢谢。
