### ISSUE TITLE
感觉对https无解

### ISSUE THREAD

**Issue by szmtcjm** [Riant/host-switch-plus#31]
你好~
最近我也在开发类似的插件，感觉https无解啊~~
我的理解是楼主用Fiddler测试是因为Fiddler本身支持代理(下面两篇文章)，不知道是不是这样

https://imququ.com/post/web-proxy.html
https://imququ.com/post/web-proxy-2.html

**Comment by Riant** [comment]
嗯，谢谢你，这些我倒是没有深入研究。

**Comment by peterleng** [comment]
https的域名访问不能支持吗？

**Comment by Riant** [comment]
@lengyufeng 代理目标服务器也支持 https 的话，倒是可以测试一下。

@szmtcjm 我感觉不是 Fiddler 本身支持代理，而是 Fiddler 本身也支持 https
