### ISSUE TITLE
你好，批量添加域名IP对应关系时，加入tag标志

### ISSUE THREAD

**Issue by nottellyou** [Riant/host-switch-plus#32]
你好，批量添加域名IP对应关系时，加入tag标志。目前只能一个一个加，累死人。

**Comment by Riant** [comment]
Bulk Add 选项卡下可以批量加咯。
每条分别为 IP, Domain, Tags, Note，使用空格隔开；多个标签使用英文逗号,隔开，如：
`127.0.0.1:1080 *.xyz.com VPN,Shadowsocket`
