### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by xstable** [Riant/host-switch-plus#37]
Is it possible to support https?

**Comment by Riant** [comment]
Please make sure you target server has supported https.

**Comment by tmarly** [comment]
Indeed the https seems to be not supported: I have a website supporting both http & https, when I browse HTTP, the IP used is the one defined in Host-Switch-Plus, and when I browse in HTTPS, the IP used is the one defined on public DNS servers.

Tested on Chrome 54.0.2840.100, Ubuntu 16.04, and in Private browsing mode to make sure there is no DNS cache.

**Comment by Riant** [comment]
Yes, you  should make sure the IP and domin you defined in Host-Switch-Plus has https support, too.

**Comment by pjalvesbr** [comment]
When using HTTPS the extension is not redirecting to the desired server, causing timeout. Servers are compatible with HTTPS.
