### ISSUE TITLE
请问插件支持https的重定向么？要如何才能支持？

### ISSUE THREAD

**Issue by peterleng** [Riant/host-switch-plus#39]
如题

**Comment by Riant** [comment]
由于我这里没有 https 服务器，所以目前尚未完整测试对 https 的支持，从大量用户的反馈来看，不完全支持。目前能够确认，我测试过的是：
1. 支持 Fiddler 的代理；
2. 支持类似 Shadowsocks 工具的代理

进一步的其他情况，欢迎测试反馈。

由于插件完全使用 Chrome 的代理模式，所以，其他不支持的情况，暂时应该没有比较好的办法。

**Comment by Riant** [comment]
#31  这个也可以看一下
