### ISSUE TITLE
请问默认的tag可以删除么

### ISSUE THREAD

**Issue by libmw** [Riant/host-switch-plus#4]
作者辛苦了，请问默认的prod，dev，test可以删除么

**Comment by Riant** [comment]
谢谢反馈，

对 Tag 的支持比较简单，后期看看再说吧，或者考虑在 tag 显示那里做一下优化， 0项tag 不显示会不会好一些呢？

**Comment by Riant** [comment]
请更新至 1.3.10，已经在设置页面移除了默认 Tag, 并在操作页面不显示 0 项 Tag。
