### ISSUE TITLE
【请教】请问修改host是怎么实现的？

### ISSUE THREAD

**Issue by fynixw** [Riant/host-switch-plus#40]
打算写一个chrome插件，需要用到切换域名所对应的远程ip地址。

找到作者的这个插件，看了下源码，没太明白作者怎么实现强制设置远程ip的。

background.js里的代码我打断点后根本不会触发。。

```
var enableHosts = [];

chrome.webRequest.onCompleted.addListener(function (details) {
    //data[details.tabId] = details.ip;
    setTimeout(function(){
        details.req = 'showip';
        details.hosts = enableHosts;
        chrome.tabs.sendRequest(details.tabId, details, function (response) {
            // console.log('res:', response);
        });
    },1000);
}, {
    urls: [ 'http://*/*', 'https://*/*' ],
    types: [ 'main_frame' ]
});

chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    enableHosts = request;
});
```

求教>~.~<

**Comment by Riant** [comment]
Chrome 的代理插件，一般使用的都是 Chrome 的 chrome.proxy 接口哈（https://developer.chrome.com/extensions/proxy , 中文版：https://crxdoc-zh.appspot.com/extensions/proxy  ），这里使用的是 pac_script 模式。

源码的话，主要你可以参考 host-switch-plus/js/model.js 文件的 344 行 chrome.proxy.settings.set() 及其上下文哈。

因为这个配置是在你修改，添加，切换代理规则的时候处理的，所以你跟踪 Background.js 跟踪不到哈，你可以跟踪弹出层内容页面的 model.js。
