### ISSUE TITLE
代理失效，增加个自定义代理吧。

### ISSUE THREAD

**Issue by wilon** [Riant/host-switch-plus#41]
mode只有direct和system，增加个代理选项

**Comment by Riant** [comment]
没明白您说的意思。
direct 和 system 是指插件启用的时候，未设置或者启用的访问是直接访问还是通过系统配置访问。

如果要代理某个域名或者某类域名，请直接设置并启用 域名/IP 代理规则。

**Comment by wilon** [comment]
https://github.com/getlantern/lantern

用了Lantern，可以上Google了，但打开此插件就上不去了。其他浏览器能上。

**Comment by Riant** [comment]
哦，我查了一下，Lantern 在我本地的代理端口是 56922， 所以，您可以将您需要代理的域名配置代理至该软件，具体比如：
```
127.0.0.1:56922    *.google*.com    Lantern
127.0.0.1:56922	   *.gstatic.com    Lantern
```
或者也可以设置为全部代理，并在需要的时候开启：
```
127.0.0.1:56922    *    Lantern
```

**Comment by Riant** [comment]
Lantern 在本地的代理端口号，可以打开 显示蓝灯 > 设置 > 高级设置 找到。

**Comment by wilon** [comment]
多谢，完美解决问题。
