### ISSUE TITLE
Default 选项是干嘛用的？

### ISSUE THREAD

**Issue by huangnaiang** [Riant/host-switch-plus#44]
选了Direct和System感觉没区别

**Comment by Riant** [comment]
嗯，Default 的本意是设置对于未匹配的 URL 采用何种连接方式，是直接链接，还是通过系统代理设置连接：这只是根据 Chrome 代理接口文档弄的，我测试了下，貌似有时候也不是很灵光，不过一直没有找原因。

如果你没有系统层面的代理配置，确实是没有区别的，不用太关心。
