### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by huangnaiang** [Riant/host-switch-plus#45]
![1111](https://cloud.githubusercontent.com/assets/1285426/21489559/f67b860e-cc26-11e6-85a3-10607d5494c3.png)

如图，配置了10.125.42.41 averyhuang.oa.com 如果这个host配置配到hosts文件是没问题的，走host switch plus就会报这个错误。10.125.42.41:80是一个apache，只转发请求，会转发到10.125.42.41:8888上 也是一台apache

**Comment by Riant** [comment]
嗯，插件的代理实现 和 直接配置系统 Hosts 文件 确实是不一样的；

服务器端的转发机制我不是很清楚，可能需要服务器端 Debug 一下看看问题出在哪里，或者也可以尝试直接配置 ```10.125.42.41:8888 averyhuang.oa.com``` ；

不行的话，这种情况还是使用 hosts 文件配置吧。
