### ISSUE TITLE
望能支持 端口号后项目名的映射

### ISSUE THREAD

**Issue by yu530feng** [Riant/host-switch-plus#47]
实际开发中往往是 （ip+端口号+项目名）对应 一个域名，希望本插件能支持添加项目名的映射，从而不需要nginx代理配置（前端人员一般不用这个，虽然用fiddler等工具也能解决，但麻烦）

**Comment by Riant** [comment]
哈哈，该插件只是间接实现浏览器代理而已，主要解决同一个域名需要经常变更 IP 指向的开发需求，而系统 hosts 更新又不能实时生效的问题，并不包含 Web Server。所以服务方面还是要使用 nginx 的，毕竟我们也不经常增加项目。
