### ISSUE TITLE
添加批量数据，会造成内存耗尽

### ISSUE THREAD

**Issue by lovitus** [Riant/host-switch-plus#48]
严重问题：一次添加几千行hosts记录，在task manager看到内存逐渐升高，最后耗尽了机器的内存（chromebook）。
暂时不知道该是否能工作正常，毕竟无法添加需要的所有项。

瑕疵：另外 有注释＃和空行会被停止解析，需要用shell重新整理才能batch导入。

**Comment by Riant** [comment]
几千行 hosts 记录，可能该插件不大适合您的需要。建议将不经常变动指向的 hosts 配置写入系统 hosts 文件，这样也能获得更高的解析性能，毕竟插件为了配置实时生效，都是每次请求实时循环匹配的。

注释 # 不影响解析，空行暂时没有处理，有望下一个版本完善，谢谢。
