### ISSUE TITLE
这个扩展改掉了请求的头信息？

### ISSUE THREAD

**Issue by wang745125665** [Riant/host-switch-plus#49]
使用插件获取到的REQUEST_URI是包含了域名部分的，导致一些项目不能正常运行，比如设置www.example.com到本地后，得到的`REQUEST_URI`是`http://www.example.com`，改本地host的是`/`，为何要这样做？这样不就跟改本地host文件不同了吗

**Comment by Riant** [comment]
插件使用的是浏览器提供的代理 API, 是和本地系统 hosts 文件有区别的。

**Comment by wang745125665** [comment]
好吧，我以为这插件是可以代替改host文件的，没想到修改了头信息导致服务器端出错

**Comment by Riant** [comment]
后端需要获取请求 host 的地方会出问题，建议初始化好后端项目相关信息之后再使用该插件，或者如果后端总是需要获取该类请求头信息，请阅读插件说明，使用提及的其他 hosts 管理软件，比如 SwitchHosts! 谢谢。
