### ISSUE TITLE
在360浏览器用，会导致无法使用代理服务器

### ISSUE THREAD

**Issue by zlxyc** [Riant/host-switch-plus#50]
在360浏览器用，会导致无法使用代理服务器

**Comment by Riant** [comment]
在其他 Chrome 系浏览器使用也会导致无法链接代理服务器，毕竟插件本身就是一个代理配置，当然也比较好解决，可以在插件中将您需要代理的域名设置代理至您所说的代理服务器。
比如我是使用的 Shadowsocks ，可以在插件中设置如下：
```
127.0.0.1:1080	*.google*.com	 Google, Shadowsocket	
127.0.0.1:1080	*.gstatic.com	 Google, Shadowsocket
127.0.0.1:1080	*.twitter.com     twitter, Shadowsocket
127.0.0.1:1080	*.facebook.*	 Shadowsocket
```
其中 1080 即为代理服务的本地端口号，具体需要看你本地代理服务器的设置，可能有所不同。
