### ISSUE TITLE
这插件开启后，如果本地使用其他代理工具后，该代理工具不生效，貌似冲突了？

### ISSUE THREAD

**Issue by qinshanxue** [Riant/host-switch-plus#51]
如题

**Comment by Riant** [comment]
本地的其他代理工具是指？
理论上来说，本地代理工具一般是通过自动设置 IE 浏览器的代理规则进行网络访问代理的，这就要检查一下 Google 浏览器是不是设置了使用 IE 浏览器代理；也就是一般情况下本地的代理工具不会影响到 Chrome 的代理配置；
另外还要确认一下 Chrome 是不是安装了其他代理插件，因为按 Chrome 的插件使用规范，多个代理类插件只会有一个生效，也会导致该插件不生效。

**Comment by cai-q** [comment]
同样的问题，本机使用ss代理，用了插件后ss代理失效。插件代理设置成disable也没用，必须从拓展列表里面停掉才行。

**Comment by Riant** [comment]
使用 ss 代理的话，可以在插件中将需要ss代理的域名设置代理至 `127.0.0.1:1080`，其中 1080 为 ss 的本地代理端口，具体请检查您自己的 ss 的代理端口配置（以 Windows Shadowsocks 为例，双击任务栏小飞机图标，出现配置界面右下角即有 代理端口配置）。

在插件配置中设置如下（空格隔开，分别是代理IP:端口、代理域名、标签）：
```
127.0.0.1:1080	 *.facebook.*   ss
127.0.0.1:1080	 *.google*.*     ss
127.0.0.1:1080	 *.gstatic.com  ss
```
