### ISSUE TITLE
只是在当前浏览器访问环境中生效吗？

### ISSUE THREAD

**Issue by hugtale** [Riant/host-switch-plus#52]
我是做php开发的，本地后台还会去请求其他测试环境的host，但发现本地后台请求的host并没切换至测试环境。不知道是不是基于的什么代理原理的问题

**Comment by Riant** [comment]
浏览器插件，当然是只能在相应浏览器下生效的。

代理实现是基于 Chrome 浏览器的代理接口实现的，本插件使用 pac_script 模式，和直接修改系统 hosts 文件有本质区别哈。具体文档可以看 [Google官方文档](https://developer.chrome.com/extensions/proxy)
