### ISSUE TITLE
希望支持列表的排序和域名去重功能

### ISSUE THREAD

**Issue by hugtale** [Riant/host-switch-plus#53]
列表有排序功能的话，可以更方便查找。最简单的方式就按域名的字典排序也是好的。

域名去重功能。可能同时添加了同一个域名，这个情况下，双击全部开关会有问题。

如果能合并相同域名的标签就更好了！

**Comment by Riant** [comment]
很多时候相同域名会分别指向不同的 host 配置，以便在不同时候切换使用，这也是插件初衷，
所以对于相同域名的配置，只是做了同一时间，只能开启其中之一的处理。

排序后边加上 :)
