### ISSUE TITLE
无法同时和shadowsocks同时使用

### ISSUE THREAD

**Issue by bb7788** [Riant/host-switch-plus#56]
插件很好用！
但是无法同时和shadowsocks同时使用，要使用ss的时候必须关闭这个插件才行，这个问题能解决么。

**Comment by Riant** [comment]
https://github.com/Riant/host-switch-plus/issues/23

设置相关域名的代理规则，比如：
```
127.0.0.1:1080	*.twitter.com		
127.0.0.1:1080	*.google*.com		
127.0.0.1:1080	*.facebook.*
```

其中 1080 为 Shadowsocks 的本地代理端口
