### ISSUE TITLE
Does not appear to work with HTTPS/SSL traffic

### ISSUE THREAD

**Issue by xyloguy** [Riant/host-switch-plus#6]
The plugin does not appear to work with HTTPS/SSL traffic. I have a sever with SSL configured, but if I switch from HTTP to HTTPS it is unable to perform a DNS lookup for a host record. Any suggests or fixes?

**Comment by Riant** [comment]
@xyloguy  Hi, Thanks for ur feedback.

Please make sure the plugin version is 1.3.9, I think I had fix that issue.
But I did not do too much test about that, only tested that with ShadowSocks and Fiddler. I used these 2 tools often.

The screenshot below is the https test with Fiddler, it's running on my localhost:8888:
![2016-01-15_101026](https://cloud.githubusercontent.com/assets/668285/12343619/5c03a60a-bb70-11e5-9abe-6f609c4006db.png)

**Comment by lancelotgit** [comment]
HTTPS/SSL is not working for me - i use version 1.3.9

**Comment by Riant** [comment]
As you know, Browser facebook, Google is difficult for us in China, shadowsocket is a good choice for me.

Check the screenshot below, it looks working well.

![2016-09-09_155908](https://cloud.githubusercontent.com/assets/668285/18379716/7efb1a70-76a6-11e6-8df8-8ed3a5eff439.png)
