### ISSUE TITLE
Enable选项不生效

### ISSUE THREAD

**Issue by sunmingshuai** [Riant/host-switch-plus#63]
host-switch-plus跟我的SwitchyOmega代理冲突了 看到你说重装host-switch-plus就可以了 因为chrome默认后装的获得代理权 我重装后 发现SwitchyOmega不能用了 原因是一直被后装的host-switch-plus给占用了  我把Enable选项取消掉 也不行 看来是这个Enable选项并没有实际的取消掉 希望能解决 谢谢

**Comment by Riant** [comment]
受制于 Chrome 代理规则：代理类插件同一时间仅能有一个生效哈，如果都开启，那么一般是后安装的生效。

你可以尝试使用 Chrome 的扩展程序管理功能去启用/禁用某个插件哈。

另外，host-switch-plus 应该可以替代 SwitchyOmega 的部分功能哈，实在没必要两个都装上。
