### ISSUE TITLE
使用插件会导致Shadowsocks失效

### ISSUE THREAD

**Issue by vq0599** [Riant/host-switch-plus#69]
Hello,
平常工作中使用Shadowsocks翻墙，但是似乎开启了Host Switch Plus会导致Shadowsocks失效。
请求都被Host Switch Plus拦截了就不能被Shadowsocks代理了吗？
请问了解这种情况吗？谢谢。
系统：Mac 10.12.3

**Comment by Riant** [comment]
#23
#56
