### ISSUE TITLE
使用时，和SwitchOmega插件冲突

### ISSUE THREAD

**Issue by RandalTeng** [Riant/host-switch-plus#70]
定义host完了，开启SwitchyOmega转发的时候，本应该被HostSwitchPlus转发到本地的localhost.*域名，被转发到SwithyOmega插件的代理端口

**Comment by noname007** [comment]
我这里是，直接都不起效了。

**Comment by Riant** [comment]
是的，2个插件本质都是一样的，只是适用场景不同，导致某个会更便利好理解，原则上，可以互相替代。
按 Chrome 规则，代理类扩展，只会有一个生效，一般是后安装的那个生效
