### ISSUE TITLE
插件开启后，更改代理方式为system，会导致ss在chrome无效

### ISSUE THREAD

**Issue by cikichen** [Riant/host-switch-plus#8]
之前一直通过Proxy SwitchyOmega设置为系统代理来使用ss，但是因为和host switch冲突，所以关闭swithcomega，把host switch的代理方式设置为system，但是发现无效，无法正常使用设置好的系统pac

我所使用的环境的osx10.11

**Comment by rockxsj** [comment]
跟系统没关系  因为chrome/chromium限制只能用一个插件管理代理   我也为这事头疼   因为开发过程中这两个插件都是比较常用的

**Comment by Riant** [comment]
@cikichen  

您说的 ss 是 Shadowsocks 吗？可以通过添加并启用如下代理规则来走 ss 系统代理。

> 127.0.0.1:1080    *

也有可能你机子上的 ss 代理端口不是 1080，可以双击状态栏 ss 图标，打开配置界面查看。

**Comment by Riant** [comment]
@rockxsj 

是的，代理插件只能同时启用一个，这也是我改进这个插件试图同时支持 host 和本地代理端口的原因。ShadowSocks 的配置和我在说明中说的 Fiddler 配置类似的，只是注意代理端口不一样。
