### ISSUE TITLE
建议：希望增加显示IP功能

### ISSUE THREAD

**Issue by henry24264** [Riant/host-switch-plus#9]
插件很不错，很好用，希望增加显示当前页面的IP功能，类似 host manager 左下角展示比较明显的IP地址。

**Comment by Riant** [comment]
@henry24264  这个，在下一版考虑加入哈。

**Comment by henry24264** [comment]
提前赞一个，呵呵

**Comment by lh4111** [comment]
可以先用 Server IP 这个插件代替

**Comment by Riant** [comment]
请更新至 1.3.10，已支持显示

**Comment by henry24264** [comment]
是的，已经支持被代理的IP展示了，很不错，谢谢
